# -*- coding: utf-8 -*-
"""Cópia de Atividades IF ELIF ELSE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pia-8TAKWYRJ9rrjYiFP5OothMlmq5ks
"""

x=6+4*2
print(x)

x=(4*9+5)
print(x)

x=((6+7)*9)
print(x)

x=(15+20-30)
print(x)

x=(6+5**2)
print("x =",x)

x=8
print(x)
x+=5
print(x)
x-=4
print(x)
x*=20
print(x)
x/=2
print(x)



x=8
print(x)
x1=3
print(x1)
ct=x<x1
print(ct)
x_result=x==x1
print(x_result)
x_result=x>=x1
print(x_result)
x_result=x!=x1
print(x_result)



"""OPERADORES DE COMPARACAO

"""

x1="botafogo"
x2="flamengo"
x3="botafogo"

xresult_1 = x1 is x3
xresult_2 = x1 is not x2
xresult_3 = x1 is x2
xresult_4 = x2 is not x3

print(xresult_1)
print(xresult_2)
print(xresult_3)
print(xresult_4)

frutas=["banana","laranja","uva","abacaxi"]

x1="banana"
x2="laranja"
x3="abaxaxi"

xresult_1 = x1 in frutas
xresult_2 = x1 not in frutas
xresult_3 = x2 not in frutas
xresult_4 = x3 in frutas

print(xresult_1)
print(xresult_2)
print(xresult_3)
print(xresult_4)



x=4
x1=9
x2=5

xresult = (((2+5)*3)+x+5)<x1
print(xresult)

x=4
x1=9
x2=5

xresult = ((2+5*3)+(x+5<x1)==(x==6+x2*2))
print(xresult)



x=4
x1=9
x2=5

xresult= (((3*6)+x-3)<x2)
print(xresult)

x=4
x1=9
x2=5

xresult = (((7*8)>(x+4-x1)<(x*2+x2*9)))
print(xresult)

n= 32


print(n<20 or n>30)



a = 15
b = 10
ab = a>10 and b<=5
print (ab)

a = 15
b = 10
ab = a>10 or b<=5

print (ab)

ler duas notas de um aluno, efetuar a media aritmetica e, caso a media seja maior ou igual a 7, informar que o aluno foi aprovado. (pseudocodigo e python)

pseudocodigo

se
nota_1 = 8
nota_2 = 7,5

se (media aluno >=7)
 entao
 aluno aprovado
  senao
  aluno reprovado

fim_se



#Python

nota_1 = 8 float (imput) vai receber um valor real vindo de uma entrada de dados
nota_2 = 7.5

result = (nota_1 + nota_2)/2 # variavel media vai receber a soma das variaveis nota e nota 2 dividido por 2
if (result) >= 7: # se a variavel media for maior ou igual a 7
    print ("aprovado") (f"a media do aluno e{media:.2f}")
    print (f"situacao do aluno: {aluno}")
else:
  print ("reprovado")

Exercicios
1

nota_1= 5
nota_2= 10

result = (nota_1 + nota_2)/2
if (result) > 15:
  print ("aprovado")
else:
  print ("reprovado")

nota1 = float(input("Digite a primeira nota"))
nota2 = float(input("Digite a segunda nota"))

soma = (nota1 + nota2)

if soma > 15:
    print (soma)

2

valor_1 = float(input("Digite a primeira nota"))
if valor_1 > 0:
  print("positivo")

elif valor_1 < 0:
  print("negativo")

else:
  print("neutro")

"""leia a idade e diga se a pessoa e maior ou menor de idade"""

idade_1 = float(input("Digite a idade "))

if idade_1 >= 18:
  print("maior de idade")

elif idade_1 < 18:
  print("menor de idade")

Faça um programa que pergunte a temperatura atual para o usuário e mostre uma
mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.

temp_1 = float(input("Qual a temperatura atual"))

if temp_1 > 30:
  print("quente")

elif temp_1>= 20:
    print("agradavel")

else:
  print("frio")

Faça um programa em linguagem Python que leia dois números inteiros e informe
se estes são iguais ou diferentes

nint_1 = float(input("digite o primeiro numero "))
nint_2 = float(input("digite o segundo numero "))

if nint_1== nint_2:
  print("os numeros sao iguais")

else:
  print("os numeros sao diferentes")

Escreva um programa que verifique a validade de uma senha fornecida pelo
usuário. A senha válida é o número 1234. Devem ser impressas as seguintes
mensagens: ACESSO PERMITIDO caso a senha seja válida.
 ACESSO NEGADO caso a senha seja inválida

usuario = float(input("Digite seu usuario: "))
senha = 1234
if  usuario == senha:
  print("senha valida")

else:
  print("senha invalida")

Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou
igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas
menor do que 7, informar que o aluno está de exame; se a média for menor do que
5 informar que o aluno foi reprovado

nota_1 = 8
nota_2 = 7
result = (nota_1 + nota_2)/2

if result >= 7:
    print("aprovado")

elif result >= 5:
    print(" esta de exame")

else:
    print("reprovado")

Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os
gols de cada time) e informe se o resultado foi um empate, se a vitória foi do
primeiro time ou do segundo time.

pj_1 = float(input("placar do jogo de futebol"))
pj_2 = 2

if pj_1 > pj_2:
  print("vitoria primeiro time")

else:
  print("vitoria do segundo time")

9- Faça um Programa que pergunte em que turno você estuda. Peça para digitar Mmatutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa
Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso

turno_estudo = str(input("Qual o seu turno de estudo ?"))

if turno_estudo == "m" or turno_estudo == "matutino":
  print ("Bom dia ! ")

elif turno_estudo == "v" or turno_estudo == "vespertino":
  print ("Boa tarde ! ")

elif turno_estudo == "n" or turno_estudo == "noturno":
  print ("Boa noite ! ")

else:
  print ("Valor invalido")

"""10- Faça um programa que solicite ao usuário sua idade, depois disso, exiba a classificação etária de acordo com as faixas de valores:  Criança para 0 até 11 anos;  Adolescente para 12 até 18 anos;  Jovem para 19 até 24 anos;  Adulto para 25 até 40 anos;  Meia Idade para 41 até 60 anos;  Idoso acima de 60 anos."""

idade = float(input("Digite sua idade "))

if idade > 60:
  print("Idoso ")

elif idade >= 41 or idade <= 60:
  print("meia idade")

elif idade >= 25 or idade <= 40:
  print("Adulto ")

elif idade >=19 or idade <= 24:
  print("Jovem ")

elif idade >= 12 or idade <= 18:
  print("Adolescente ")

elif idade >= 0 or idade <= 11:
  print("Crianca")

"""11- As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contrataram para desenvolver o programa que calculará os reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:  salários até R 280,00(incluindo):aumentode20saláriosentreR  280,00 e R 700,00:aumentode15saláriosentreR  700,00 e R 1500,00:aumentode10saláriosdeR  1500,00 em diante : aumento de 5% Após o aumento ser realizado, informe na tela:  o salário antes do reajuste;  o percentual de aumento aplicado;  o valor do aumento;  o novo salário, após o aumento"""

salario_colaborador = float(input("Digite seu salario? "))

if salario_colaborador > 1500:
  aumento = 5
  print("5%")

elif salario_colaborador > 700:
  aumento = 20
  print("10%")

elif salario_colaborador > 280:
  aumento = 15
  print("15%")

elif salario_colaborador <= 280:
  aumento = 20
  print("20%")

"""12- Faça um Programa que leia um número e exiba o dia correspondente da semana. (1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido."""

diadasemana = str(input("Diga qual o dia da semana? "))

if diadasemana == "segunda":
  print("Terca-feira ")

elif diadasemana == "terca":
  print("Quarta-feira ")

elif diadasemana == "quarta":
  print("Quinta-feira ")

elif diadasemana == "quinta":
  print("Sexta-feira ")

elif diadasemana == "sexta":
  print("Sabado ")

elif diadasemana == "sabado":
  print("Domingo ")

else:
  print("Amanha será Segunda-feira ")

"""13- Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta do usuário, faça a devida conversão."""

converter = input("Deseja converter a temperatura de Fahreinheit para Celsius? ")
fahreinheit = float(input("Digite a temperatura em fahreinheit: "))
celsius = float(input("Digite a temperatura em celsius: "))

if converter == "FC":
  fahreinheit = float(input("Digite a temperatura em Fahreinheit: "))
  celsius = (Fahreinheit - 32) * 5/9
  print(f"A temperatura em Celsius é: {Celsius:.2f} °C")

elif converter == "CF":
  Celsius = float(input("Digite a temperatura em Celsius: "))
  fahreinheit = ( Celsius - 32) * 5/9
  print(f"A temperatura em Fahrenheit é: {Fahrenheit:.2f} °C ")

else:
  print ("Opção inválida. Por favor digite "FC" ou "CF" . ")

"""14- Faça um programa que receba a idade de uma pessoa e imprima sua condição (obrigatória, optativa ou proibida), em relação ao ato de votar, conforme apresentado abaixo:  Pessoas com idade menor que 16 anos são proibidas de votar (proibido);  Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar (optativo);  Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar (obrigatório);  Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo)."""

idade = int(input("Digite sua idade "))

if idade > 65:
  print("Voto optativo ")

elif idade >= 18 or idade < 65:
  print("Voto obrigatorio ")

elif idade >= 16 or idade < 18:
  print ("Voto optativo ")

elif idade < 16:
  print("Proibido votar ")

"""15- Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:  “Telefonou para a vítima? “  “Esteve no local do crime?”  “Mora perto da vítima? “  “Devia para a vítima? “  “Já trabalhou com a vítima? “"""

perguntas = ("Responda as seguintes perguntas com sim ou não: ")
pergunta1 = input("Telefonou para a vitima? "). lower()
pergunta2 = input("Esteve no local do crime? "). lower()
pergunta3 = input("Mora perto da vítima? "). lower()
pergunta4 = input("Devia para a vítima? "). lower()
pergunta5 = input("Já trabalhou com a vítima? "). lower()

positiva = 0

if pergunta1 == "sim":
   positiva += 1

if pergunta2 == "sim":
   positiva += 1

if pergunta3 == "sim":
   positiva += 1

if pergunta4 == "sim":
   positiva += 1

if pergunta5 == "sim":
   positiva += 1

else:
  print("não conhece a vitima")

"""16- O programa deve no final emitir uma classificação sobre a participação da pessoa no crime. Se a pessoa responder positivamente a 2 questões ela deve ser classificada como “Suspeita”, entre 3 e 4 como “Cúmplice” e 5 como “Assassino“. Caso contrário, ele será classificado como “Inocente“."""

perguntas = ("Responda as seguintes perguntas com sim ou não: ")
pergunta1 = input("Telefonou para a vitima? "). lower()
pergunta2 = input("Esteve no local do crime? "). lower()
pergunta3 = input("Mora perto da vítima? "). lower()
pergunta4 = input("Devia para a vítima? "). lower()
pergunta5 = input("Já trabalhou com a vítima? "). lower()

positiva = 0

if pergunta1 == "sim":
   positiva += 1

if pergunta2 == "sim":
   positiva += 1

if pergunta3 == "sim":
   positiva += 1

if pergunta4 == "sim":
   positiva += 1

if pergunta5 == "sim":
   positiva += 1

if positiva == 2:
   print("Suspeita")

elif positiva >= 3 and positiva <= 4:
   print("Cumplice")

elif positiva == 5:
   print("Bandidinho")

else:
   print("Inocente")

"""17- Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato."""

preco = float(input("Qual o preço do produto "))

produto1 = 10
produto2 = 20
produto3 = 30

if produto1 > 10:
   print("não comprar")

if produto2 > 20:
   print("não comprar")

if produto3 > 30:
   print("não comprar")

elif produto1 < 10:
   print("comprar o produto")

elif produto2 < 20:
   print("comprar o produto")

elif produto3 < 30:
   print("comprar o produto")

else:
   print("Qual o preço do produto1, produto2, produto3 ? ")